In [17]:
import torch
import math

In [32]:
r = torch.tensor([-0.02,0.03,-0.01])

In [33]:
r_min = torch.min(r)
r_mid = r.mean()
print(r_min)
print(r_mid)

tensor(-0.0200)
tensor(0.)


In [34]:
N = 5
N_pre = 2

In [35]:
for j in range(N):
    k_j = r_mid-math.pow((j-N_pre)/N,1)*(r_mid-r_min)
    w = 1/(1+torch.exp(k_j-r))
    print(k_j)
    print(w)

tensor(0.0080)
tensor([0.4930, 0.5055, 0.4955])
tensor(0.0040)
tensor([0.4940, 0.5065, 0.4965])
tensor(0.)
tensor([0.4950, 0.5075, 0.4975])
tensor(-0.0040)
tensor([0.4960, 0.5085, 0.4985])
tensor(-0.0080)
tensor([0.4970, 0.5095, 0.4995])
